apiVersion: v1
kind: Pod
metadata:
  name: address-validation-svc
  labels:
    app: address-validation-svc
spec:
  containers:
  - name: address-validation-svc
    image: japu/address-validation-svc:latest
    imagePullPolicy: "Always"
    ports:
    - containerPort: 9080
    env:
    - name: JAEGER_SERVICE_NAME
      value: "address-validation-svc"
    - name: JAEGER_AGENT_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: JAEGER_REPORTER_LOG_SPANS
      value: "true"
    - name: JAEGER_SAMPLER_TYPE
      value: "const"
    - name: JAEGER_SAMPLER_PARAM
      value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: address-validation-svc
spec:
  type: NodePort
  selector:
    app: address-validation-svc
  ports:
  - port: 9083
    targetPort: 9080
    nodePort: 30030