apiVersion: v1
kind: Pod
metadata:
  name: address-validation-svc
  labels:
    app: address-validation-svc
spec:
  containers:
  - name: address-validation-svc
    image: japu/address-validation-svc:latest
    imagePullPolicy: "Always"
    ports:
    - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: address-validation-svc
spec:
  type: NodePort
  selector:
    app: address-validation-svc
  ports:
  - port: 9083
    targetPort: 9080
    nodePort: 30030