apiVersion: v1
kind: Pod
metadata:
  name: backend4frontend
  labels:
    app: backend4frontend
spec:
  containers:
  - name: backend4frontend
    image: japu/backend4frontend:latest
    imagePullPolicy: "Always"
    ports:
    - containerPort: 9080
    env:
    - name: BA_ORDER_SERVICE_URL
      value: "http://order-svc:9081/"
    - name: BA_CART_SERVICE_URL
      value: "http://cart-svc:9082/"
    - name: BA_TRANSLATION_SERVICE_URL
      value: "http://localization-svc:9085/"
---
apiVersion: v1
kind: Service
metadata:
  name: backend4frontend
spec:
  type: NodePort
  selector:
    app: backend4frontend
  ports:
  - port: 9080
    targetPort: 9080
    nodePort: 30000