apiVersion: v1
kind: Pod
metadata:
  name: backend4frontend
  labels:
    app: backend4frontend
spec:
  containers:
  - name: backend4frontend
    image: japu/backend4frontend:latest
    imagePullPolicy: "Always"
    ports:
    - containerPort: 9080
    env:
    - name: BA_ORDER_SERVICE_URL
      value: "http://order-svc:9081/"
    - name: BA_CART_SERVICE_URL
      value: "http://cart-svc:9082/"
    - name: BA_ADDRESSVALIDATION_SERVICE_URL
      value: "http://address-validation-svc:9083/"
    - name: BA_LOCALIZATION_SERVICE_URL
      value: "http://localization-svc:9085/"
    - name: JAEGER_SERVICE_NAME
      value: "backend4frontend"
    - name: JAEGER_AGENT_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: JAEGER_REPORTER_LOG_SPANS
      value: "true"
    - name: JAEGER_SAMPLER_TYPE
      value: "const"
    - name: JAEGER_SAMPLER_PARAM
      value: "1"
    - name: SPLUNK_HEC_URL
      value: "https://splunk-s1-standalone-service:8088/"
    - name: SPLUNK_HEC_TOKEN
      valueFrom:
        secretKeyRef:
          name: splunk-default-secret
          key: hec_token
    - name: OTEL_EXPORT_HOST
      value: "jaeger-ui-collector"
    - name: OTEL_EXPORT_PORT
      value: "14250"
---
apiVersion: v1
kind: Service
metadata:
  name: backend4frontend
spec:
  type: NodePort
  selector:
    app: backend4frontend
  ports:
  - port: 9080
    targetPort: 9080
    nodePort: 30000