apiVersion: v1
kind: Pod
metadata:
  name: cart-svc
  labels:
    app: cart-svc
spec:
  containers:
  - name: cart-svc
    image: japu/cart-svc:latest
    imagePullPolicy: "Always"
    ports:
    - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: cart-svc
spec:
  type: NodePort
  selector:
    app: cart-svc
  ports:
  - port: 9082
    targetPort: 9080
    nodePort: 30020