apiVersion: v1
kind: Pod
metadata:
  name: cart-svc
  labels:
    app: cart-svc
spec:
  containers:
  - name: cart-svc
    image: japu/cart-svc:latest
    imagePullPolicy: "Always"
    ports:
    - containerPort: 9080
    env:
    - name: JAEGER_SERVICE_NAME
      value: "address-validation-svc"
    - name: JAEGER_AGENT_HOST
      value: "jaeger-ui-agent"
    - name: JAEGER_REPORTER_LOG_SPANS
      value: "true"
    - name: JAEGER_SAMPLER_TYPE
      value: "const"
    - name: JAEGER_SAMPLER_PARAM
      value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: cart-svc
spec:
  type: NodePort
  selector:
    app: cart-svc
  ports:
  - port: 9082
    targetPort: 9080
    nodePort: 30020