apiVersion: apps/v1
kind: Deployment
metadata:
  name: localization-svc
  labels:
    app: localization-svc
spec:
  replicas: 4
  selector:
    matchLabels:
      app: localization-svc
  template:
    metadata:
      labels:
        app: localization-svc
    spec:
      containers:
      - name: localization-svc
        image: japu/localization-svc:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 9080
        env:
        - name: IS_ILL_POD
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: localization-svc
spec:
  type: LoadBalancer
  selector:
    app: localization-svc
  ports:
  - port: 9085
    targetPort: 9080
    nodePort: 30050