apiVersion: v1
kind: Pod
metadata:
  name: localization-svc-001
  labels:
    app: localization-svc
spec:
  containers:
  - name: localization-svc
    image: japu/localization-svc:latest
    imagePullPolicy: "Always"
    ports:
    - containerPort: 9080
    env:
    - name: IS_ILL_POD
      value: "false"
    - name: JAEGER_SERVICE_NAME
      value: "localization-svc-001"
    - name: JAEGER_AGENT_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: JAEGER_REPORTER_LOG_SPANS
      value: "true"
    - name: JAEGER_SAMPLER_TYPE
      value: "const"
    - name: JAEGER_SAMPLER_PARAM
      value: "1"
---
apiVersion: v1
kind: Pod
metadata:
  name: localization-svc-002
  labels:
    app: localization-svc
spec:
  containers:
  - name: localization-svc
    image: japu/localization-svc:latest
    imagePullPolicy: "Always"
    ports:
    - containerPort: 9080
    env:
    - name: IS_ILL_POD
      value: "false"
    - name: JAEGER_SERVICE_NAME
      value: "localization-svc-002"
    - name: JAEGER_AGENT_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: JAEGER_REPORTER_LOG_SPANS
      value: "true"
    - name: JAEGER_SAMPLER_TYPE
      value: "const"
    - name: JAEGER_SAMPLER_PARAM
      value: "1"
---
apiVersion: v1
kind: Pod
metadata:
  name: localization-svc-003
  labels:
    app: localization-svc
spec:
  containers:
  - name: localization-svc
    image: japu/localization-svc:latest
    imagePullPolicy: "Always"
    ports:
    - containerPort: 9080
    env:
    - name: IS_ILL_POD
      value: "true"
    - name: JAEGER_SERVICE_NAME
      value: "localization-svc-003"
    - name: JAEGER_AGENT_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: JAEGER_REPORTER_LOG_SPANS
      value: "true"
    - name: JAEGER_SAMPLER_TYPE
      value: "const"
    - name: JAEGER_SAMPLER_PARAM
      value: "1"
---
apiVersion: v1
kind: Pod
metadata:
  name: localization-svc-004
  labels:
    app: localization-svc
spec:
  containers:
  - name: localization-svc
    image: japu/localization-svc:latest
    imagePullPolicy: "Always"
    ports:
    - containerPort: 9080
    env:
    - name: IS_ILL_POD
      value: "false"
    - name: JAEGER_SERVICE_NAME
      value: "localization-svc-004"
    - name: JAEGER_AGENT_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: JAEGER_REPORTER_LOG_SPANS
      value: "true"
    - name: JAEGER_SAMPLER_TYPE
      value: "const"
    - name: JAEGER_SAMPLER_PARAM
      value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: localization-svc
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-type: "none"
    service.beta.kubernetes.io/do-loadbalancer-enable-backend-keepalive: "false"
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  sessionAffinity: "None"
  selector:
    app: localization-svc
  ports:
  - port: 9085
    targetPort: 9080
    nodePort: 30050