apiVersion: v1
kind: Pod
metadata:
  name: order-svc
  labels:
    app: order-svc
spec:
  containers:
  - name: order-svc
    image: japu/order-svc:latest
    imagePullPolicy: "Always"
    ports:
    - containerPort: 9080
    env:
    - name: BA_CART_SERVICE_URL
      value: "http://cart-svc:9082/"
    - name: BA_ADDRESSVALIDATION_SERVICE_URL
      value: "http://address-validation-svc:9083/"
    - name: JAEGER_SERVICE_NAME
      value: "order-svc"
    - name: JAEGER_AGENT_HOST
      value: "jaeger-ui-agent"
    - name: JAEGER_REPORTER_LOG_SPANS
      value: "true"
    - name: JAEGER_SAMPLER_TYPE
      value: "const"
    - name: JAEGER_SAMPLER_PARAM
      value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: order-svc
spec:
  type: NodePort
  selector:
    app: order-svc
  ports:
  - port: 9081
    targetPort: 9080
    nodePort: 30010